apiVersion: v1
kind: LimitRange
metadata:
  name: preview-limits
  namespace: {{ .Values.namespace.name | quote }}
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: {{ .Values.limits.defaultRequestCpu | quote }}
        memory: {{ .Values.limits.defaultRequestMemory | quote }}
      default:
        cpu: {{ .Values.limits.defaultCpu | quote }}
        memory: {{ .Values.limits.defaultMemory | quote }}
