apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name | quote }}
  labels:
    portable-agent.io/environment: preview
    portable-agent.io/pull-request: {{ .Values.namespace.pullRequest | quote }}
  annotations:
    portable-agent.io/expires-at: {{ .Values.namespace.expiresAt | quote }}
