apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: preview-default-deny
  namespace: {{ .Values.namespace.name | quote }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
